### ISSUE TITLE
Compiling!

### ISSUE THREAD

**Issue by CkyLua** [gurka/tibia-dll-injector#1]
I have several errors while compiling, you can create a project build for Visual Studio?

**Comment by CkyLua** [comment]
1>------ Rebuild All started: Project: Project2, Configuration: Debug Win32 ------
1>  xtea.cpp
1>c:\users\windows\downloads\tibia-dll-injector-master\tibia-dll-injector-master\tibia-dll-injector\src\xtea.cpp(13): warning C4018: '<' : signed/unsigned mismatch
1>  tibia_dll_injector.cc
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(96): warning C4005: 'AF_IPX' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(452) : see previous definition of 'AF_IPX'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(136): warning C4005: 'AF_MAX' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(471) : see previous definition of 'AF_MAX'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(173): warning C4005: 'SO_DONTLINGER' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(394) : see previous definition of 'SO_DONTLINGER'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(217): error C2011: 'sockaddr' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(477) : see declaration of 'sockaddr'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(414): error C2059: syntax error : 'constant'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(414): error C3805: 'constant': unexpected token, expected either '}' or a ','
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(549): warning C4005: 'IN_CLASSA' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(279) : see previous definition of 'IN_CLASSA'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(555): warning C4005: 'IN_CLASSB' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(285) : see previous definition of 'IN_CLASSB'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(561): warning C4005: 'IN_CLASSC' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(291) : see previous definition of 'IN_CLASSC'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(572): warning C4005: 'INADDR_ANY' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(296) : see previous definition of 'INADDR_ANY'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(574): warning C4005: 'INADDR_BROADCAST' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(298) : see previous definition of 'INADDR_BROADCAST'
1>c:\program files (x86)\windows kits\8.1\include\shared\ws2def.h(608): error C2011: 'sockaddr_in' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(304) : see declaration of 'sockaddr_in'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(125): error C2011: 'fd_set' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(60) : see declaration of 'fd_set'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(145): warning C4005: 'FD_CLR' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(89) : see previous definition of 'FD_CLR'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(160): warning C4005: 'FD_SET' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(94) : see previous definition of 'FD_SET'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(169): error C2011: 'timeval' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(103) : see declaration of 'timeval'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(225): error C2011: 'hostent' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(159) : see declaration of 'hostent'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(238): error C2011: 'netent' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(172) : see declaration of 'netent'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(245): error C2011: 'servent' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(179) : see declaration of 'servent'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(257): error C2011: 'protoent' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(191) : see declaration of 'protoent'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(353): error C2011: 'WSAData' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(314) : see declaration of 'WSAData'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(451): error C2011: 'sockproto' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(486) : see declaration of 'sockproto'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(493): error C2011: 'linger' : 'struct' type redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(523) : see declaration of 'linger'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(506): warning C4005: 'SOMAXCONN' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(536) : see previous definition of 'SOMAXCONN'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(540): warning C4005: 'FD_READ' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(554) : see previous definition of 'FD_READ'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(543): warning C4005: 'FD_WRITE' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(555) : see previous definition of 'FD_WRITE'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(546): warning C4005: 'FD_OOB' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(556) : see previous definition of 'FD_OOB'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(549): warning C4005: 'FD_ACCEPT' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(557) : see previous definition of 'FD_ACCEPT'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(552): warning C4005: 'FD_CONNECT' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(558) : see previous definition of 'FD_CONNECT'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(555): warning C4005: 'FD_CLOSE' : macro redefinition
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(559) : see previous definition of 'FD_CLOSE'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1581): error C2375: 'accept' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(734) : see declaration of 'accept'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1603): error C2375: 'bind' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(739) : see declaration of 'bind'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1622): error C2375: 'closesocket' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(744) : see declaration of 'closesocket'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1641): error C2375: 'connect' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(746) : see declaration of 'connect'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1662): error C2375: 'ioctlsocket' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(751) : see declaration of 'ioctlsocket'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1683): error C2375: 'getpeername' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(756) : see declaration of 'getpeername'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1704): error C2375: 'getsockname' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(761) : see declaration of 'getsockname'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1727): error C2375: 'getsockopt' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(766) : see declaration of 'getsockopt'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1748): error C2375: 'htonl' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(773) : see declaration of 'htonl'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1765): error C2375: 'htons' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(775) : see declaration of 'htons'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1782): error C2375: 'inet_addr' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(777) : see declaration of 'inet_addr'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1799): error C2375: 'inet_ntoa' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(779) : see declaration of 'inet_ntoa'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1900): error C2375: 'listen' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(781) : see declaration of 'listen'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1918): error C2375: 'ntohl' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(785) : see declaration of 'ntohl'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1935): error C2375: 'ntohs' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(787) : see declaration of 'ntohs'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1955): error C2375: 'recv' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(789) : see declaration of 'recv'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1980): error C2375: 'recvfrom' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(795) : see declaration of 'recvfrom'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2006): error C2375: 'select' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(803) : see declaration of 'select'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2030): error C2375: 'send' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(810) : see declaration of 'send'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2055): error C2375: 'sendto' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(816) : see declaration of 'sendto'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2081): error C2375: 'setsockopt' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(824) : see declaration of 'setsockopt'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2103): error C2375: 'shutdown' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(831) : see declaration of 'shutdown'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2124): error C2375: 'socket' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(835) : see declaration of 'socket'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2148): error C2375: 'gethostbyaddr' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(842) : see declaration of 'gethostbyaddr'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2167): error C2375: 'gethostbyname' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(847) : see declaration of 'gethostbyname'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2185): error C2375: 'gethostname' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(849) : see declaration of 'gethostname'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2225): error C2375: 'getservbyport' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(853) : see declaration of 'getservbyport'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2244): error C2375: 'getservbyname' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(857) : see declaration of 'getservbyname'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2262): error C2375: 'getprotobynumber' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(861) : see declaration of 'getprotobynumber'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2279): error C2375: 'getprotobyname' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(863) : see declaration of 'getprotobyname'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2300): error C2375: 'WSAStartup' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(867) : see declaration of 'WSAStartup'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2319): error C2375: 'WSACleanup' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(871) : see declaration of 'WSACleanup'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2336): error C2375: 'WSASetLastError' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(873) : see declaration of 'WSASetLastError'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2353): error C2375: 'WSAGetLastError' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(875) : see declaration of 'WSAGetLastError'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2370): error C2375: 'WSAIsBlocking' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(877) : see declaration of 'WSAIsBlocking'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2387): error C2375: 'WSAUnhookBlockingHook' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(879) : see declaration of 'WSAUnhookBlockingHook'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2404): error C2375: 'WSASetBlockingHook' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(881) : see declaration of 'WSASetBlockingHook'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2421): error C2375: 'WSACancelBlockingCall' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(883) : see declaration of 'WSACancelBlockingCall'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2443): error C2375: 'WSAAsyncGetServByName' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(885) : see declaration of 'WSAAsyncGetServByName'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2470): error C2375: 'WSAAsyncGetServByPort' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(893) : see declaration of 'WSAAsyncGetServByPort'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2496): error C2375: 'WSAAsyncGetProtoByName' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(901) : see declaration of 'WSAAsyncGetProtoByName'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2521): error C2375: 'WSAAsyncGetProtoByNumber' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(908) : see declaration of 'WSAAsyncGetProtoByNumber'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2546): error C2375: 'WSAAsyncGetHostByName' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(915) : see declaration of 'WSAAsyncGetHostByName'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2573): error C2375: 'WSAAsyncGetHostByAddr' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(922) : see declaration of 'WSAAsyncGetHostByAddr'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2596): error C2375: 'WSACancelAsyncRequest' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(931) : see declaration of 'WSACancelAsyncRequest'
1>c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2616): error C2375: 'WSAAsyncSelect' : redefinition; different linkage
1>          c:\program files (x86)\windows kits\8.1\include\um\winsock.h(933) : see declaration of 'WSAAsyncSelect'
1>c:\users\windows 7 ultimete\downloads\tibia-dll-injector-master\tibia-dll-injector-master\tibia-dll-injector\src\tibia_dll_injector.cc(9): fatal error C1083: Cannot open include file: 'packet.h': No such file or directory
1>  server.cc
1>  rsa.cc
1>c:\users\windows\downloads\tibia-dll-injector-master\tibia-dll-injector-master\tibia-dll-injector\src\rsa.h(4): fatal error C1083: Cannot open include file: 'gmp.h': No such file or directory
1>  Generating Code...
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by gurka** [comment]
Hi,

It seems there are three problems:
1. Signed/unsigned mismatch in xtea.cpp. I guess this is only a warning?
2. Both winsock.h and winsock2.h are included, causing redeclarations. I have no idea why this happens.
3. You need the gmp library (https://gmplib.org/) to compile rsa.cc. However, that file isn't really used atm so it should be safe to delete it or just remove it from the compilation / project.

What version of Visual Studio do you use? I guess I can install it and create a project for it, if I find the time to do it.

**Comment by CkyLua** [comment]
VS Express 2013...

I am not able to use, could better explain how it works? 
It would be nice if he took all versions of the tibia 8.60 to the current version or versions starting 10.5+

**Comment by CkyLua** [comment]
I want to get these codes to complete a SharpMapTracker 
ClientRsa = client.BaseAddress + = NAME? 
ClientServerStart = client.BaseAddress + = NAME? 
ClientServerEnd = client.BaseAddress + = NAME?

EX:
ClientSelectedCharacter = client.BaseAddress + 0x55414C; = adrSelectedCharIndex
ClientStatus = client.BaseAddress + 0x3CBC3C; = adrConnected=&H(7)CBC3C

**Comment by CkyLua** [comment]
???????????
