### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CkyLua** [gurka/tibia-dll-injector#2]
![sem titulo](https://cloud.githubusercontent.com/assets/8111601/4303508/5b2a8cd0-3e67-11e4-9097-6460cdb66e7c.png)

**Comment by gurka** [comment]
What mingw/gcc version are you using? Do you see any error message like: "error: unrecognized command line option "-std=c++11""? My guess is that your gcc doesn't support --std=c++11. You should try changing it to --std=c++0x.
